// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"1920","screenHeight":"1080","changeWindowWidthTo":"1920","changeWindowHeightTo":"1080","renderingMode":"auto","alwaysDash":"off"}},
{"name":"bentelk_FullScreenOptions","status":true,"description":"Adds a \"Full Screen\" option to the Options window","parameters":{}},
{"name":"bentelk_TransparentTitleMenu","status":true,"description":"Makes the title menu window transparent, and allows you to position it.","parameters":{}},
{"name":"bentelk_WideScreen","status":true,"description":"Makes some changes that are appropriate for 16:9 resolutions.","parameters":{}},
{"name":"ItemBook","status":true,"description":"Displays detailed statuses of items.","parameters":{"Unknown Data":"??????","Price Text":"Price","Equip Text":"Equip","Type Text":"Type"}}
];
